### ISSUE TITLE
Connectivity status

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-xamarin#10]
on my app I was registering the following tags:

* connection.wifi [true/empty]
* connection.bluetooth [true/empty]
* connection.cellular [true/empty]
* connection.ethernet [true/empty]
* connection.unknown [true/empty]

@bruno-garcia  should I add something like that to Sentry Xamarin?

**Comment by bruno-garcia** [comment]
@lucas-zimerman what about the tag: `connectivity.type` and value be `wifi` or the other value?

**Comment by lucas-zimerman** [comment]
TODO: Investigate how to retrieve those values from Native Platforms.
