### ISSUE TITLE
add app start instrumentation for xamarin (forms)

### ISSUE THREAD

**Issue by hot33331** [getsentry/sentry-xamarin#104]
For native android/ios and flutter app start instrumentation is already implemented. This is also a very important KPI for Xamarin and would be highly appreciated.

**Comment by lucas-zimerman** [comment]
This and #106 are going to be solved once we integrate the Sentry Xamarin SDK with the Native SDKs

**Comment by hot33331** [comment]
Any rough timeline on that?

**Comment by bruno-garcia** [comment]
do you have plans to move to MAUI? 
Apps are supposedly easy to convert, and MAUI is GA"ing soon.

We are very interested in investing in MAUI going forward and adding the native crash support straight into the .NET (e.g: https://github.com/getsentry/sentry-dotnet/pull/1288) and we'd love to collaborate with the community on this

**Comment by hot33331** [comment]
Hi Bruno, yes, since Xamarin support will be discontinued 1 year after GA (as far as I know), we will switch to MAUI. No concrete timeline on that so far though, since dates for GA of MAUI were vage (Q2/22) and changing (e.g. from .net 6 GA to Q22). I guess within 1 year after GA... ;-)  How can I help?

**Comment by bruno-garcia** [comment]
We track MAUI here: https://github.com/getsentry/sentry-dotnet/issues/1174

**Comment by mattjohnsonpint** [comment]
Hi.  We won't fix this for Xamarin, but will for MAUI (getsentry/sentry-dotnet#1174).  Thanks.
