### ISSUE TITLE
add Routing Instumentation for App Shell in Xamarin Forms

### ISSUE THREAD

**Issue by hot33331** [getsentry/sentry-xamarin#105]
App shell does also have routing and it would be an important KPI to measure the time it takes navigating between pages.

**Comment by lucas-zimerman** [comment]
That surely would be a nice Feature to the Sentry SDK

**Comment by bruno-garcia** [comment]
Xamarin is out of support by Microsoft. So while we're happy to take PRs here and get a new release out with fixes. We won't be making big investments here and instead invest on .NET Mobile and MAUI.
