### ISSUE TITLE
add Slow and Frozen Frames instrumentation for xamarin

### ISSUE THREAD

**Issue by hot33331** [getsentry/sentry-xamarin#106]
This feature exists on native and flutter and would also be a great kpi to have for Xamarin (forms).

**Comment by bruno-garcia** [comment]
Xamarin is out of support by Microsoft. So while we're happy to take PRs here and get a new release out with fixes. We won't be making big investments here and instead invest on .NET Mobile and MAUI.

We do plan on adding this specific feature on MAUI btw.
