### ISSUE TITLE
Update to sentry.dotnet@v3.19.0 with Forms???

### ISSUE THREAD

**Issue by hot33331** [getsentry/sentry-xamarin#123]
I am using Sentry.Xamarin.Forms 1.4.1 and in my dashboard I get the following warning:

This project is on sentry.dotnet@v3.17.1
[Update to sentry.dotnet@v3.19.0](https://docs.sentry.io/platforms/dotnet)

This is not a bug, but I would not know what to do there... How can I update - should I / do I need to update?
I guess the update would need to be done within the sentry.xamarin.forms package, right?

**Comment by bruno-garcia** [comment]
That's correct. This update notifier is a bit annoying when we bundle SDKs together like `Sentry.Xamarin` that depends on [`Sentry`](https://github.com/getsentry/sentry-dotnet).

It's safe to ignore this notifications though

**Comment by bruno-garcia** [comment]
That said, if you'd like to make a PR here updating the SDK, we'll gladly merge and make a release

**Comment by hot33331** [comment]
> That said, if you'd like to make a PR here updating the SDK, we'll gladly merge and make a release

Sorry, just read that now. Thanks for upping the version!
