### ISSUE TITLE
Sentry.Xamarin 1.4.2 gives error when compiling against net6.0-android project

### ISSUE THREAD

**Issue by kmiterror** [getsentry/sentry-xamarin#126]
### Environment

Visual Studio for Mac 17.3
M1 CPU
macOS Monterey

### Steps to Reproduce

1. Bump sentry.xamarin to version 1.4.2
2. compile

### Expected Result
project should compile 

### Actual Result
During compilation it finishes with 182 instances of errors like below:
`obj/Debug/net6.0-android31.0/Resource.designer.cs(4,4): Error CS0433: The type 'Resource' exists in both 'Sentry.Xamarin, Version=1.4.2.0, Culture=neutral, PublicKeyToken=null' and 'Sentry, Version=3.20.1.0, Culture=neutral, PublicKeyToken=fba2ec45388e2af0' (CS0433)`

After downgrading to 1.4.1 it works properly

**Comment by lucas-zimerman** [comment]
Hi kmiterror. This package will not support .NET 6 Android/iOS, the support was added to the main Package and the MAUI package (https://github.com/getsentry/sentry-dotnet) so I'd recommend migrating to the Sentry Maui SDK

**Comment by lucas-zimerman** [comment]
Closing as we are not going to addsupport to .NET 6 on this SDK but on the main SDK.
