### ISSUE TITLE
Setup Github Action for testing UWP

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-xamarin#13]
Right now there's a project for testing the SDK with UWP, but it's not integrated with Github Actions.

It would be great to integrate it so future Pull Requests will be checked against UWP.

**Comment by bruno-garcia** [comment]
@lucas-zimerman isn't this resolved?

**Comment by lucas-zimerman** [comment]
mmm, @bruno-garcia there's no Github Action for tests. You were helping with it but I can't recall the status of it.

**Comment by bruno-garcia** [comment]
Leaving it up-for-grabs for now, I'm not familiar with UWP so someone who knows it better might be able to do it faster than me

**Comment by bruno-garcia** [comment]
Xamarin is out of support by Microsoft. So while we're happy to take PRs here and get a new release out with fixes. We won't be making big investments here and instead invest on .NET Mobile and MAUI.
