### ISSUE TITLE
SDK doesn't allow you to overwrite the release option

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-xamarin#132]
After a quick glance here, I noticed this code doesn't allow the user to overwrite the release version
https://github.com/getsentry/sentry-xamarin/blob/main/Src/Sentry.Xamarin/SentryXamarin.cs#L26

**Comment by bruno-garcia** [comment]
Xamarin is out of support by Microsoft. So while we're happy to take PRs here and get a new release out with fixes. We won't be making big investments here and instead invest on .NET Mobile and MAUI.
