### ISSUE TITLE
Line numbers for Android

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry-xamarin#134]
With Sentry.Xamarin 1.4.6, we are using Sentry 3.26.2, which ([when configured](https://docs.sentry.io/platforms/dotnet/configuration/cli-integration/)) will upload symbols to Sentry during a release build.  This part appears to work fine.

In testing, I found that filenames and line numbers are appearing for iOS Xamarin apps now, but not for Android Xamarin apps.

I believe this is because we aren't sending any of the `DebugImage` information in the stack frames with the exceptions.  We do this for Android on MAUI (or any `net6.0-android` or `net7.0-android` app), but not for traditional Xamarin apps.

It should be possible to fix this, either by sharing source code from Sentry .NET (`DebugStackTrace`, `AndroidAssemblyReader`, etc.) or by modifying the code in Sentry to detect Android environment at runtime instead of compiling it only for `net6.0-android`.

**Comment by mattjohnsonpint** [comment]
Upstream issue: https://github.com/getsentry/sentry-dotnet/issues/2126

**Comment by lucas-zimerman** [comment]
If it doesn't require a lot of changes, sharing the source code could ideal, unless the environment detection doesn't have a huge impact in performance for the other platforms.

**Comment by mattjohnsonpint** [comment]
@vaind - thoughts?

**Comment by mattjohnsonpint** [comment]
I've been doing some experimentation, and I think a good approach would be to split [`Sentry.Android.AssemblyReader`](https://github.com/getsentry/sentry-dotnet/tree/main/src/Sentry/Platforms/Android/AssemblyReader) namespace out to its own Nuget package, targeting `netstandard2.1`.  We'd then take a dependency on that from both `Sentry/net6.0-android` and `Sentry.Xamarin/monodroid9.0`.

(I did try just creating a `monodroid9.0` target of `Sentry`, but that's not possible with the dotnet SDK).

To share the code, we can add `SentryOptions.AssemblyReader`, of type `Func<string, PEReader?>?`, and wire it to the Android assembly reader during initialization.

I think the assembly reader should be in its own GitHub repository also, so it can rev versions independently.  That will also move the apk tests so they don't need to run on every Sentry build.  Any objections?

**Comment by vaind** [comment]
Sounds good. Not sure if a split to another repo is necessary though. Is there currently only a single nuget package shipped from the sentry-dotnet repo?

**Comment by mattjohnsonpint** [comment]
No, there are several.  Just they all version and deploy together by default.  I can probably work around that though.  I'll give it a try. 👍

**Comment by vaind** [comment]
Do we need different versions though? Maybe it's ok to push even though there were no changes. I guess that also happens for other packages
