### ISSUE TITLE
XALNK7000: Mono.Linker.MarkException Sentry.SentryXamarinOptionsExtensions::RegisterXamarinEventProcessors

### ISSUE THREAD

**Issue by michaelmairegger** [getsentry/sentry-xamarin#150]
### Environment

|Package|Version|
|-|-|
|Sentry|4.4.0|
|Sentry.Xamarin.Forms|2.0.0|

### Steps to Reproduce

Have Sentry `4.4.0` and Sentry.Xamarin `2.0.0`.

Build Xamarin Android project in Release mode

### Expected Result

Build succeed

### Actual Result

|Package|Version|Build Error
|-|-|-|
|Sentry|>4.3.0|Error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Sentry.SentryXamarinOptionsExtensions::RegisterXamarinEventProcessors(Sentry.SentryXamarinOptions)' |
|Sentry|4.2.1|None|

**Comment by bitsandfoxes** [comment]
Hey @michaelmairegger, sorry to see you run into this. This looks like an unintended sideeffect of the change to the extension in https://github.com/getsentry/sentry-dotnet/pull/3195
We're going to fix this.

**Comment by michaelmairegger** [comment]
@bitsandfoxes with 2.1.0 it seems the issue is resolved
