### ISSUE TITLE
Enable Nullable Reference Types

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-xamarin#17]
Add C# 8 Nullable Reference Types. Since the framework versions in this project don't support it, we need to use a shim such as used in the .NET SDK for the TFMs below .NET Core 3.0 (where no nullability annotation exists).

https://github.com/getsentry/sentry-dotnet/blob/6ddf8363170bffee74a8c3cbf44335797d39ca9c/Directory.Build.props#L17

**Comment by bruno-garcia** [comment]
This needs a bit more clarification to get the `up-for-grabs` tag since just by reading the title, with no description it's hard to figure out the goal.

**Comment by lucas-zimerman** [comment]
Since Sentry.NET uses the Nullable package, it would be nice that Sentry.NET Xamarin would also use it.
Any better idea for the description?

**Comment by lucas-zimerman** [comment]
cccccc
