### ISSUE TITLE
NullReferenceException in SentryXamarinFormsIntegration with slow Xamarin.Forms StartUp

### ISSUE THREAD

**Issue by ZakMcGrabben** [getsentry/sentry-xamarin#57]
### Environment

Which SDK and version?
Sentry 3.0.7
Sentry.Xamarin.Forms 1.0.2

### Steps to Reproduce

1. Starting Xamarin.Forms uwp app
2. Initalizing Xamarin.Forms takes a long time.
3. Runs into NullReferenceException (see screenshot)
4. App crashes

Forcing via Thread.Sleep for easy reproducing:

```
		protected override void OnLaunched(LaunchActivatedEventArgs e)
		{
			SentryXamarin.Init(options =>
			{
				options.Dsn = SENTRY_DSN;
				options.Release = Version.Major + "." + Version.Minor;
				options.SendDefaultPii = true;
				options.AddXamarinFormsIntegration();

			});

			System.Threading.Thread.Sleep(3000);
```

### Expected Result

No Exception should be raised

### Actual Result

See Exception screenshot:
![error](https://user-images.githubusercontent.com/75368051/109489146-be30af00-7a86-11eb-86c7-1562b6da4a26.PNG)

Register() Method tries to call DiagnosticLogger, which is null, which causes the exception.

application is null, because start takes longer than 3000 ms in SentryXamarinFormsIntegration.cs:

```
        private async Task<Application> GetCurrentApplication()
        {
            for (int i = 0; i < 10 && Application.Current is null; i++)
            {
                await Task.Delay(300).ConfigureAwait(false);
            }
            return Application.Current;
        }
```

### Possible Solutions:

1. Run App on a faster computer ;-)

2. Add a Timeout / loop setting for application start. maybe reduce delay and increase loop times.

3. Add null check for  call "options.DiagnosticLogger.Log()"

### Workaround
Add options to Init:

```
	public class SentryLogger : IDiagnosticLogger
	{
		public bool IsEnabled(SentryLevel level)
		{
			return true;
		}

		public void Log(SentryLevel logLevel, string message, Exception exception = null, params object[] args)
		{
			Debug.WriteLine(message, args);
		}
	}


...
			SentryXamarin.Init(options =>
			{
				options.DiagnosticLogger = new SentryLogger();
				options.Debug = true;


...
			});
```

**Comment by lucas-zimerman** [comment]
Hi ZakMcGrabben, thank you for your report, I'll look at it and release a fix for it on the next version :)
