### ISSUE TITLE
Include screenshots with events

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-xamarin#65]
The idea is to include screenshots with events. Like this:

https://github.com/getsentry/symbol-collector/blob/e31753b68380e830bec400a97c879ff97d0f6bd9/src/SymbolCollector.Android/MainActivity.cs#L400-L437

**Comment by bruno-garcia** [comment]
We might need to add to the Sentry .NET SDK to use `Task` with attachments

**Comment by lucas-zimerman** [comment]
Closed by https://github.com/getsentry/sentry-xamarin/pull/76
