### ISSUE TITLE
Screenshot feature Ideas

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry-xamarin#79]
I created this issue to discuss some possibilities to enhance the Screenshot feature.

* Add a user option to choose the minimum event level to attach a screenshot, where the use case is a user not wanting screenshots with debug/info/warning events but error and fatal.

* Add a user option to choose the picture quality (could be a low/medium/high enum or a percentage from 1 to 100), the reasoning is, current device resolutions are getting too high and with that, screenshots are getting bigger.
[sample_pictures.zip](https://github.com/getsentry/sentry-xamarin/files/6931596/sample_pictures.zip) <- sample pictures to compare the compression quality.
By default, 50% seems to be a good balance between size and quality.

If you have any other ideas, feel free to comment.

**Comment by bruno-garcia** [comment]
Closing for now. If we decide to add new features later we can bring this back up
