### ISSUE TITLE
Screenshot with 0 bytes breaks preview

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-xamarin#86]
Latest SDK:

![image](https://user-images.githubusercontent.com/1633368/134276781-2ed0ff67-aae6-4650-ae7d-5f85ba4f164d.png)

**Comment by Mahdibenamor** [comment]
facing the same error here, with release mode, seems to be critical and breaking for the feature, cause we can't use it in production

**Comment by bruno-garcia** [comment]
This is happening when running the SDK on .NET 6 app (https://github.com/getsentry/symbol-collector) before that, it was working with the exception of a few cases.

Perhaps we must make sure the event is captured in the UI thread?
Or instead of streaming the screenshot, we should try to buffer it, and avoid adding the 0 byte attachment altogether.

**Comment by lucas-zimerman** [comment]
Waiting for the next release of the Sentry .NET to be able to fix this issue.
