### ISSUE TITLE
Crash error caused by package code (IHubExtensions.AddInternalBreadcrumb)

### ISSUE THREAD

**Issue by sondrebh** [getsentry/sentry-xamarin#88]
Our app seems to be crashing every now and then on multiple devices. This is the error reported by Sentry:

> System.ArgumentNullException: Value cannot be null.
Parameter name: first
  ?, in IEnumerable<KeyValuePair<string, string>> Enumerable.Except<KeyValuePair<string, string>>(IEnumerable<KeyValuePair<string, string>> first, IEnumerable<KeyValuePair<string, string>> second)
  ?, in void IHubExtensions.AddInternalBreadcrumb(IHub hub, SentryXamarinOptions options, string message, string category, string type, Dictionary<string, string> data, BreadcrumbLevel level)
  ?, in void NativeIntegration.<get_MemoryWarning>b__12_0(?)+(NSNotification _) => { }
  ?, in void InternalNSNotificationHandler.Post(NSNotification s)
  ?, in void UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate) x 2
  ?, in void Application.Main(string[] args)

It seems it is this code that is causing the error: (IHubExtensions.cs line: 36)
> !previousBreadcrumb.Data.Except(data).Any() &&

I guess putting in a null-conditional behind .Data would solve the issue, but it might go deeper than that?
> .Data?.Except

**Comment by lucas-zimerman** [comment]
Hi Sondrebh, thanks for opening the issue.
We'll look into it and fix it on the next version, but, feel free to open a pull request for it : )

**Comment by bruno-garcia** [comment]
Fixed on #90
