### ISSUE TITLE
Sentry.Xamarin.Forms not sending exception when application restarted on android

### ISSUE THREAD

**Issue by albilaga** [getsentry/sentry-xamarin#91]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
Sentry.Xamarin.Forms 1.3.1

### Steps to Reproduce

1. Install Sentry.Xamarin.Forms to Android and core project
2. Init in MainActivity.OnCreate
3. Throw some dummy exception in one of the page.
4. Application will crash
5. Reopen the app

### Expected Result

Exception should be sent to sentry when application restarted

### Actual Result

Exception not sent to Sentry. I attach the stacktrace so it can help. My device Xiaomi Redmi 5A (API 27)
[stacktrace.txt](https://github.com/getsentry/sentry-xamarin/files/7403317/stacktrace.txt)

**Comment by bruno-garcia** [comment]
We've documented this here: https://docs.sentry.io/platforms/dotnet/guides/xamarin/troubleshooting/#android
