### ISSUE TITLE
[BUG][PROD][Release] Screenshot are attached with 0 size in release mode

### ISSUE THREAD

**Issue by Mahdibenamor** [getsentry/sentry-xamarin#95]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
sentry xamarin SDK 1.3.1

### Steps to Reproduce

1- integrate sentry SDK into android xamarin app, and activate the screenshot feature.
2- generate a random error in debug mode 
3- generate a random error in release mode

### Expected Result

you can see screenshot in debug mode, and you can't see screenshot in release mode

### Actual Result

you can see screenshot in debug mode, and you can't see screenshot in release mode

![image](https://user-images.githubusercontent.com/43537755/148560938-c1addbf3-1107-4bbb-bf5b-995e848961d2.png)

**Comment by lucas-zimerman** [comment]
Hi Mahdibenamor.
Are you capturing this error before or after the splash screen was completed?
Also, could you share you enable Debug on  SentryOptions and share your log from logcat?

**Comment by bruno-garcia** [comment]
I also had issues on symbol collector. How did you make it work?
